# DOT_START

# Enable extended globbing
setopt extended_glob

# Load the shell dotfiles
# (~/.extra) can be used for other settings you don't want to commit.
for dot_file in ~/.{exports,aliases,functions,extra}; do
  source "${dot_file}"
done

# Base16 shell script for configuring colors
source ~/bin/base16-tomorrow.dark.sh

# Prompt: https://github.com/sindresorhus/pure
prompt pure

# Shortcuts
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word
bindkey \^U backward-kill-line
bindkey '\e_' insert-last-word

# Enable completion for various commands
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
#source $(brew --prefix awscli)/libexec/bin/aws_zsh_completer.sh
#source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Neither of the below work...
source <(kubectl completion zsh | sed '/"-f"/d')
#source <(kubectl completion zsh)
#source <(eksctl completion zsh)

# History settings
unsetopt inc_append_history
unsetopt share_history
