tap "buildkite/buildkite"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/versions"
tap "olafurpg/scalafmt"
tap "paulp/extras"
tap "weaveworks/tap"
brew "ammonite-repl"
brew "awscli"
brew "bash"
brew "gettext"
brew "clamav"
brew "coreutils"
brew "cscope"
brew "curl"
brew "go"
brew "dep"
brew "docker-machine-driver-xhyve"
brew "dos2unix"
brew "findutils"
brew "gawk"
brew "git"
brew "git-lfs"
brew "giter8"
brew "gnu-getopt"
brew "gnu-indent", args: ["with-default-names"]
brew "gnu-sed"
brew "gnu-tar", args: ["with-default-names"]
brew "gnutls"
brew "pkg-config"
brew "gradle"
brew "groovy"
brew "haskell-stack"
brew "htop"
brew "hub"
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "kube-ps1"
brew "kubectx", args: ["with-short-names"]
brew "kubernetes-helm"
brew "leiningen"
brew "libidn"
brew "libssh2"
brew "libyaml"
brew "logstash"
brew "lua"
brew "macvim", args: ["with-override-system-vim"]
brew "maven"
brew "mill"
brew "moreutils"
brew "nasm"
brew "node"
brew "nvm"
brew "orc-tools"
brew "packer"
brew "pipenv"
brew "q"
brew "ruby", link: true
brew "rust"
brew "sbt"
brew "scala"
brew "snappy"
brew "telnet"
brew "tree"
brew "unrar"
brew "wget"
brew "yarn"
brew "buildkite/buildkite/buildkite-agent", args: ["token="]
brew "olafurpg/scalafmt/scalafmt", args: ["HEAD"]
brew "paulp/extras/coursier", args: ["HEAD"]
brew "weaveworks/tap/eksctl"
cask "minikube"
